apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hzv5cx1dh-java-quarkus
  janus-idp.io/tekton: hzv5cx1dh-java-quarkus
  backstage.io/kubernetes-id: hzv5cx1dh-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hzv5cx1dh-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
